# --- General ---
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-ghostty:Tc"
set -g allow-passthrough on
set -g mouse on
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on
set -g escape-time 0
set -s extended-keys on
set -as terminal-features 'xterm-ghostty:extkeys'
bind-key -n S-Enter send-keys Escape "[13;2u"

# --- Prefix ---
set -g prefix C-a
unbind C-b
bind C-a send-prefix

# --- Splits ---
bind d split-window -h -c "#{pane_current_path}"
bind D split-window -v -c "#{pane_current_path}"

# --- vim-tmux-navigator ---
# Smart pane switching with awareness of Vim splits.
is_vim="ps -o state= -o comm= -t '#{pane_tty}' | grep -iqE '^[^TXZ ]+ +(\\S+\\/)?g?(view|l?n?vim?x?|fzf)(diff)?$'"
bind-key -n 'C-h' if-shell "$is_vim" 'send-keys C-h' 'select-pane -L'
bind-key -n 'C-j' if-shell "$is_vim" 'send-keys C-j' 'select-pane -D'
bind-key -n 'C-k' if-shell "$is_vim" 'send-keys C-k' 'select-pane -U'
bind-key -n 'C-l' if-shell "$is_vim" 'send-keys C-l' 'select-pane -R'

# --- Windows ---
bind c new-window -c "#{pane_current_path}"
bind n next-window
bind p previous-window

# --- Clear screen ---
bind k send-keys -R \; clear-history \; send-keys Enter

# --- Plugins ---
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'janoamaral/tokyo-night-tmux'
set -g @tokyo-night-tmux_window_id_style none
set -g @tokyo-night-tmux_pane_id_style none

# --- Reload config ---
bind r source-file ~/.config/tmux/tmux.conf \; display "Config reloaded"

# Initialize TPM (keep at bottom)
run '~/.config/tmux/plugins/tpm/tpm'
